// <auto-generated />
using System;
using Loreggia.Delivery.Track.Autenticador.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Loreggia.Delivery.Track.Autenticador.Repository.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Loreggia.Delivery.Track.Autenticador.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("codigo")
                        .HasColumnType("uuid");

                    b.Property<bool>("Apagado")
                        .HasColumnName("apagado")
                        .HasColumnType("boolean");

                    b.Property<int?>("CodigoEmpresa")
                        .HasColumnName("codigo_empresa")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnName("dataDeCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnName("email_verificado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnName("nome")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnName("senha")
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
